compatibility_date = "2021-10-21"
type = "javascript"
name = "worker-template"
account_id = "46ab19cd500a15d82064f994954a1b6e"
zone_id = "f7535f65ab4a03cf9336606ebe4afb80"
workers_dev = true
routes = ["https://api.collabhack.com/item*", "https://api.collabhack.com/version*"]
vars = { }
port = 8787

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
main = "./_worker.js"

[env.wrangler]
workers_dev = true
account_id = "abcdefg01234567890"
vars = {  }

[env.miniflare]
vars = { }
durable_objects.bindings = [

]

[miniflare]
durable_objects_persist = "./.miniflare/durable-objects/"
kv_persist = "./.miniflare/kv/"
